repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.45.0
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode # use 2.8.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.0

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 36.23.0
    hooks:
      - id: renovate-config-validator

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.25
    hooks:
      - id: actionlint
