---
name: Test
run-name: "Test on \"${{ github.event.pull_request.title }}\" by ${{ github.actor }}"

permissions:
  contents: read
  packages: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  init__node:
    name: "Initialize: node"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies-and-cache

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs:
      - init__node
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies-and-cache
      - uses: ./.github/actions/build-and-cache

  test__code_spec:
    name: "Code Specifigation"
    runs-on: ubuntu-latest
    needs:
      - init__node
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies-and-cache
      - run: yarn test:spec


  test__definition_types_spec:
    name: "Definition Types Specifigation"
    runs-on: ubuntu-latest
    needs:
      - init__node
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies-and-cache
      - run: yarn test:spec-d


  test__typecheck:
    name: "TypeCheck"
    runs-on: ubuntu-latest
    needs:
      - init__node
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies-and-cache
      - run: yarn test:type
